[package]
name = "nebula_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
bevy = "0.10.1"
bevy_fly_camera = "0.10.0"
if_chain = "1.0.2"
